# Generated by Django 4.0.4 on 2022-07-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(blank=True, null=True, verbose_name='descuento'),
        ),
    ]
